import React from 'react';
import { ShieldCheck, Calendar, ShieldAlert, FileText, ChevronRight } from 'lucide-react';

const DISEASE_METADATA = {
  'Actinic_Keratosis': {
    code: 'akiec',
    severity: 'Warning',
    badgeClass: 'badge-warning',
    description: 'Actinic Keratosis is a rough, scaly patch on the skin that develops from years of sun exposure. It is considered pre-cancerous, as it can occasionally progress to squamous cell carcinoma if left untreated.',
    action: 'Schedule a routine visit with a dermatologist for evaluation. Avoid sun exposure and wear sunscreen.'
  },
  'Basal_Cell_Carcinoma': {
    code: 'bcc',
    severity: 'Danger',
    badgeClass: 'badge-danger',
    description: 'Basal Cell Carcinoma is a type of skin cancer that begins in the basal cells. It is the most common form of skin cancer, usually growing slowly and rarely spreading to other parts of the body, but causes local damage.',
    action: 'Dermatologist visit required. A biopsy and minor surgical removal are standard options.'
  },
  'Benign_Keratosis': {
    code: 'bkl',
    severity: 'Success',
    badgeClass: 'badge-success',
    description: 'Benign Keratosis-like Lesions include seborrheic keratosis, which are non-cancerous skin growths that occur in older adults. They appear as waxy, scaly, or crusty spots.',
    action: 'No immediate clinical intervention needed unless irritated or for cosmetic preference.'
  },
  'Dermatofibroma': {
    code: 'df',
    severity: 'Success',
    badgeClass: 'badge-success',
    description: 'Dermatofibromas are common, harmless, firm, red-to-brown bumps that typically occur on the lower legs. They are benign fibrous nodules.',
    action: 'Benign lesion. No treatment is needed unless it becomes painful or undergoes rapid changes.'
  },
  'Melanoma': {
    code: 'mel',
    severity: 'Danger',
    badgeClass: 'badge-danger',
    description: 'Melanoma is the most serious type of skin cancer. It develops in the melanocytes (cells producing pigment) and can quickly metastasize to other organs if not caught early.',
    action: 'Urgent evaluation by a dermatologist is highly recommended. Immediate biopsy or excision is standard procedure.'
  },
  'Melanocytic_Nevi': {
    code: 'nv',
    severity: 'Success',
    badgeClass: 'badge-success',
    description: 'Melanocytic Nevi, commonly known as common moles, are benign tumors of melanocytes. They are extremely common and harmless, though atypical moles require monitoring.',
    action: 'Normal mole. Keep an eye on it using the ABCDE guidelines (Asymmetry, Border, Color, Diameter, Evolving).'
  },
  'Vascular_Lesion': {
    code: 'vasc',
    severity: 'Success',
    badgeClass: 'badge-success',
    description: 'Vascular Lesions include cherry angiomas, angiokeratomas, or pyogenic granulomas, which are benign skin growths made of blood vessels.',
    action: 'Benign condition. No medical action is necessary unless bleeding or cosmetic distress occurs.'
  }
};

const ResultCard = ({ results, onOpenInfo }) => {
  if (!results) {
    return (
      <div className="glass-card" style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '100%', minHeight: '350px', borderStyle: 'dashed', backgroundColor: 'transparent' }}>
        <FileText size={48} style={{ color: 'var(--text-muted)', marginBottom: '1rem' }} />
        <p style={{ fontWeight: 600, color: 'var(--text-secondary)' }}>Awaiting Diagnostic Run</p>
        <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)', textAlign: 'center', maxWidth: '240px', marginTop: '0.25rem' }}>
          Upload a skin lesion image and click 'Run Diagnostics' to view AI-generated predictions here.
        </p>
      </div>
    );
  }

  const primaryResult = results[0]; // { label: 'Melanoma', confidence: 0.85 }
  const meta = DISEASE_METADATA[primaryResult.label] || {
    code: 'unknown',
    severity: 'Warning',
    badgeClass: 'badge-warning',
    description: 'Unknown classification result. Please review diagnostic model version.',
    action: 'Consult a dermatologist for general checkups.'
  };

  const confidencePercentage = Math.round(primaryResult.confidence * 100);

  // SVG parameters for circular meter
  const radius = 70;
  const strokeWidth = 10;
  const normalizedRadius = radius - strokeWidth / 2;
  const circumference = normalizedRadius * 2 * Math.PI;
  const strokeDashoffset = circumference - (primaryResult.confidence * circumference);

  return (
    <div className="glass-card" style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
      <div className="result-header">
        <div>
          <h3 style={{ fontSize: '1.25rem', fontWeight: 700 }}>Analysis Report</h3>
          <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>Generated by HAM10000 ResNet Classifier</p>
        </div>
        <span className={`badge ${meta.badgeClass}`}>
          {meta.severity === 'Danger' && <ShieldAlert size={14} />}
          {meta.severity === 'Success' && <ShieldCheck size={14} />}
          {meta.severity === 'Warning' && <Calendar size={14} />}
          {primaryResult.label.replace('_', ' ')}
        </span>
      </div>

      <div style={{ display: 'flex', gap: '2rem', flexWrap: 'wrap', alignItems: 'center', justifyContent: 'center', padding: '1rem 0' }}>
        <div className="circular-progress">
          <svg viewBox="0 0 140 140">
            <circle
              className="bg-circle"
              r={normalizedRadius}
              cx={radius}
              cy={radius}
            />
            <circle
              className="progress-circle"
              strokeDasharray={circumference + ' ' + circumference}
              style={{ strokeDashoffset }}
              r={normalizedRadius}
              cx={radius}
              cy={radius}
              stroke={meta.severity === 'Danger' ? 'var(--color-danger)' : meta.severity === 'Warning' ? 'var(--color-warning)' : 'var(--color-primary)'}
            />
          </svg>
          <div className="progress-value">
            {confidencePercentage}%
            <span>Conf.</span>
          </div>
        </div>

        <div style={{ flex: 1, minWidth: '220px', display: 'flex', flexDirection: 'column', gap: '0.5rem', textAlign: 'left' }}>
          <h4 style={{ fontSize: '1.1rem', fontWeight: 700 }}>
            {primaryResult.label.replace('_', ' ')}
          </h4>
          <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', lineHeight: '1.4' }}>
            {meta.description.substring(0, 140)}...
            <button 
              onClick={() => onOpenInfo(primaryResult.label)} 
              style={{ color: 'var(--color-primary)', fontWeight: 600, display: 'inline-flex', alignItems: 'center', marginLeft: '0.25rem' }}
            >
              Read full details <ChevronRight size={14} />
            </button>
          </p>
        </div>
      </div>

      {/* Probability list of all predictions */}
      <div className="result-body">
        <h4 style={{ fontSize: '0.9rem', fontWeight: 700, borderBottom: '1px solid var(--border-color)', paddingBottom: '0.5rem', textAlign: 'left' }}>
          Probability Breakdown
        </h4>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '0.85rem' }}>
          {results.map((res, index) => {
            const diseaseMeta = DISEASE_METADATA[res.label] || {};
            const isTop = index === 0;
            const barColor = isTop
              ? (meta.severity === 'Danger' ? 'var(--color-danger)' : meta.severity === 'Warning' ? 'var(--color-warning)' : 'var(--color-primary)')
              : 'var(--text-muted)';

            return (
              <div key={res.label} className="prediction-item">
                <div style={{ width: '150px', textAlign: 'left', fontSize: '0.85rem', fontWeight: isTop ? 700 : 500, color: isTop ? 'var(--text-primary)' : 'var(--text-secondary)' }}>
                  {res.label.replace('_', ' ')}
                </div>
                <div className="prediction-bar-container">
                  <div 
                    className="prediction-bar" 
                    style={{ 
                      width: `${res.confidence * 100}%`, 
                      backgroundColor: barColor 
                    }}
                  ></div>
                </div>
                <div className="prediction-value" style={{ fontWeight: isTop ? 700 : 400, color: isTop ? 'var(--text-primary)' : 'var(--text-muted)' }}>
                  {(res.confidence * 100).toFixed(1)}%
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* Suggested Action Item */}
      <div 
        style={{ 
          marginTop: '0.5rem', 
          backgroundColor: 'var(--bg-primary)', 
          border: '1px solid var(--border-color)', 
          borderRadius: 'var(--radius-md)', 
          padding: '1rem',
          textAlign: 'left'
        }}
      >
        <p style={{ fontSize: '0.8rem', fontWeight: 700, color: 'var(--text-primary)', marginBottom: '0.25rem' }}>
          RECOMMENDED CLINICAL ACTION
        </p>
        <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)' }}>
          {meta.action}
        </p>
      </div>
    </div>
  );
};

export { DISEASE_METADATA };
export default ResultCard;
